import type {
  GeoScorecard,
  TechnicalAuditReport,
  FanoutOutput,
} from "../types/index.js";

const FOOTER_WATERMARK = `
---
*Generated by [open-geo](https://github.com/geofn-com/open-geo) Community Edition.*  
*Looking for 24/7 multi-model AI search monitoring, competitor gap patches, and white-label client reports? Visit [geofn.com](https://geofn.com).*
`;

/**
 * Generates an executive Markdown report for a GEO probe run
 */
export function formatGeoMarkdownReport(scorecard: GeoScorecard): string {
  const lines: string[] = [];

  const targetTitle =
    scorecard.domain && scorecard.domain !== "example.com"
      ? (scorecard.brand.toLowerCase() === scorecard.domain.toLowerCase() ||
         scorecard.brand.toLowerCase() === scorecard.domain.split(".")[0].toLowerCase())
        ? scorecard.domain
        : `${scorecard.brand} (${scorecard.domain})`
      : scorecard.brand;

  lines.push(`# 🚀 GEO Visibility Report: ${targetTitle}`);
  lines.push(
    `> Tool: \`open-geo\` Community Edition | Domain: \`${scorecard.domain}\` | Total Probes: **${scorecard.totalProbes} runs** | Generated: ${new Date().toUTCString()}`
  );
  lines.push("");

  if (scorecard.results.some((r) => r.isSimulated)) {
    lines.push(
      "> [!NOTE]\n> **Zero-Token Simulated Baseline**: This report was generated using offline heuristic patterns to verify the pipeline. For real-time multi-model evaluations with genuine search citations, configure `OPENROUTER_API_KEY` (or `GEMINI_API_KEY`) in your `.env` file.\n"
    );
  }

  const totalMentions = scorecard.results.filter((r) => r.brandMentioned).length;
  const awarenessRate = scorecard.totalProbes > 0 ? Math.round((totalMentions / scorecard.totalProbes) * 100) : 0;

  lines.push("## 📊 GEO Visibility & Funnel Metrics");
  lines.push("");
  lines.push("| Funnel Stage | Metric | Value | Rating | Interpretation |");
  lines.push("| :--- | :--- | :--- | :--- | :--- |");

  const awareRating = awarenessRate >= 80 ? "🟢 High" : awarenessRate >= 40 ? "🟡 Moderate" : "🔴 Low";
  lines.push(
    `| **Top Funnel (Awareness)** | **Brand Awareness Rate** | **${awarenessRate}%** (${totalMentions}/${scorecard.totalProbes}) | ${awareRating} | Frequency AI recognized & mentioned your brand |`
  );

  const top3Rating = scorecard.top3RecommendationRate >= 60 ? "🟢 Strong" : "🟡 Needs Improvement";
  lines.push(
    `| **Mid Funnel (Preference)** | **Top-3 Preferred Recommendation** | **${scorecard.top3RecommendationRate}%** | ${top3Rating} | Frequency AI placed brand in top 3 primary choices |`
  );

  const citeRating = scorecard.citationShare >= 40 ? "🟢 Healthy" : "🔴 Needs Optimization";
  lines.push(
    `| **Bottom Funnel (Trust)** | **Official Citation Share** | **${scorecard.citationShare}%** | ${citeRating} | Ratio of AI citations linking directly to your domain |`
  );

  const visRating =
    scorecard.visibilityScore >= 80
      ? "🟢 Excellent"
      : scorecard.visibilityScore >= 50
      ? "🟡 Moderate"
      : "🔴 Low";
  lines.push(
    `| **Composite Index** | **Overall GEO Visibility Index** | **${scorecard.visibilityScore} / 100** | ${visRating} | Weighted synthetic score across awareness, rank, and citations |`
  );
  lines.push("");

  // Strategic Funnel Diagnosis Alert
  if (awarenessRate >= 60 && scorecard.top3RecommendationRate < 40) {
    lines.push(
      `> [!TIP]\n> 💡 **GEO Diagnostic Insight: "Aware but not Preferred"**  \n> AI recognized and mentioned your brand in **${awarenessRate}%** of queries, but placed competitors in top-3 recommendations (preferred rate: **${scorecard.top3RecommendationRate}%**).  \n> **Root Cause**: AI knows of your product, but lacks authoritative feature-comparison citations and third-party benchmark references to rank you above incumbents. Deploying structured comparison data and Schema.org markup can convert mentions into top-tier recommendations.\n`
    );
  } else if (awarenessRate < 40) {
    lines.push(
      `> [!WARNING]\n> 💡 **GEO Diagnostic Insight: "Low Knowledge Ingestion"**  \n> AI search engines rarely surface your brand (**${awarenessRate}%** awareness). AI crawlers have not ingested sufficient structured data or /llms.txt specifications.\n`
    );
  } else if (scorecard.top3RecommendationRate >= 60) {
    lines.push(
      `> [!NOTE]\n> 💡 **GEO Diagnostic Insight: "Category Leader"**  \n> Strong primary positioning with **${scorecard.top3RecommendationRate}%** top-3 recommendation rate. Maintain content freshness to defend against citation drift.\n`
    );
  }

  const modelCount = Object.keys(scorecard.modelPerformance).length;
  lines.push(`## 🤖 Probe Summary (${modelCount} ${modelCount === 1 ? "Model" : "Models"})`);
  lines.push("");
  lines.push("| Model Name | Mentions / Total Probes | Awareness Rate | Domain Citations |");
  lines.push("| :--- | :--- | :--- | :--- |");
  for (const [model, stats] of Object.entries(scorecard.modelPerformance)) {
    const rate = Math.round((stats.mentionedCount / stats.total) * 100);
    lines.push(`| **${model}** | ${stats.mentionedCount} / ${stats.total} | ${rate}% | ${stats.citationCount} times |`);
  }
  lines.push("");

  if (scorecard.audit) {
    lines.push("## 🛠️ Technical Readiness Snapshot");
    lines.push("");
    lines.push("| Diagnostic Dimension | Status | Current Audit Finding |");
    lines.push("| :--- | :--- | :--- |");
    lines.push(
      `| **\`/llms.txt\` Standard** | ${scorecard.audit.llmsTxt.hasLlmsTxt ? "✅ Deployed" : "❌ Missing"} | ${scorecard.audit.llmsTxt.details} |`
    );
    lines.push(
      `| **Schema.org Structured Data** | ${scorecard.audit.schemaMarkup.hasJsonLd ? "✅ Configured" : "⚠️ Missing"} | ${scorecard.audit.schemaMarkup.details} |`
    );
    lines.push(
      `| **AI Crawler Whitelist** | ${scorecard.audit.aiCrawlability.allowsAiBots ? "✅ Allowed" : "❌ Blocked"} | ${scorecard.audit.aiCrawlability.robotsTxtStatus} |`
    );
    lines.push("");
  }

  const unrankedResults = scorecard.results.filter((r) => !r.brandMentioned);
  if (unrankedResults.length > 0) {
    lines.push("## ⚠️ Unranked Intent Scenarios (Knowledge Gaps)");
    lines.push("The AI engine omitted your brand in the following high-intent buyer inquiries:");
    lines.push("");
    lines.push("| Buyer Funnel Stage | Target Search Intent | AI Visibility Status |");
    lines.push("| :--- | :--- | :--- |");
    unrankedResults.forEach((res) => {
      const stageName =
        res.stage === "ToFU"
          ? "ToFU (Category Discovery)"
          : res.stage === "MoFU"
          ? "MoFU (Alternatives & Comparison)"
          : "BoFU (Decision & Evaluation)";
      const queryText = res.query ? `\`"${res.query}"\`` : `\`"${res.promptText.slice(0, 45)}..."\``;
      lines.push(`| **${stageName}** | ${queryText} | ❌ Unmentioned |`);
    });
    lines.push("");
  }

  lines.push("## 💡 Actionable GEO Remediation Roadmap");
  lines.push("Execute verified `open-geo` CLI commands to fix identified gaps and boost AI citations:");
  lines.push("");

  const recommendations: string[] = [];
  const targetUrl = scorecard.domain.startsWith("http") ? scorecard.domain : `https://${scorecard.domain}`;

  // 1. Audit-based: llms.txt recommendation
  if (scorecard.audit && !scorecard.audit.llmsTxt.hasLlmsTxt) {
    recommendations.push(
      `### 1. 📑 Deploy Machine-Readable \`/llms.txt\`\n` +
      `Generate standardized LLM navigation specs to enable AI search bots to crawl and cite your documentation:\n` +
      `\`\`\`bash\n` +
      `open-geo generate-llms ${targetUrl} --full\n` +
      `\`\`\`\n` +
      `*Outputs both root \`/llms.txt\` index and full-depth \`/llms-full.md\` for AI agent ingestion.*`
    );
  } else if (scorecard.citationShare < 30) {
    recommendations.push(
      `### 1. 📑 Refresh \`/llms.txt\` Specification (Citation Share: ${scorecard.citationShare}%)\n` +
      `Expand documentation depth so AI engines link directly to your official domain:\n` +
      `\`\`\`bash\n` +
      `open-geo generate-llms ${targetUrl} --full\n` +
      `\`\`\``
    );
  }

  // 2. Audit-based: Schema.org JSON-LD recommendation
  if (scorecard.audit && !scorecard.audit.schemaMarkup.hasJsonLd) {
    recommendations.push(
      `### 2. 🏷️ Inject Schema.org & FAQPage JSON-LD\n` +
      `Extract high-intent buyer Q&As and generate compliant structured data for immediate CMS injection:\n` +
      `\`\`\`bash\n` +
      `open-geo generate-faq ${targetUrl} -o ./schema-faq.md\n` +
      `\`\`\`\n` +
      `*Generates validated Schema.org FAQPage structured data blocks.*`
    );
  }

  // 3. Funnel-based: Preference Gap recommendation
  if (scorecard.top3RecommendationRate < 60) {
    recommendations.push(
      `### 3. 🎯 Close Competitor Preference Gap (Top-3 Rate: ${scorecard.top3RecommendationRate}%)\n` +
      `Decompose 5-dimensional search intents to identify comparison angles where competitors outrank you:\n` +
      `\`\`\`bash\n` +
      `open-geo fanout "${scorecard.brand}" -d "${scorecard.domain}"\n` +
      `\`\`\`\n` +
      `*Analyzes feature, pricing, and alternative comparison gaps across the buyer journey.*`
    );
  }

  // 4. Knowledge Gap based: Keywords recommendation
  if (scorecard.knowledgeGaps.length > 0) {
    const primaryGap = scorecard.knowledgeGaps[0];
    recommendations.push(
      `### 4. 🔍 Mine Long-Tail Buyer Keywords\n` +
      `Mine real-time user search suggestions to guide high-ranking comparison content creation:\n` +
      `\`\`\`bash\n` +
      `open-geo keywords "${primaryGap}"\n` +
      `\`\`\`\n` +
      `*Extracts live intent keyword clusters from Google & Bing.*`
    );
  }

  if (recommendations.length === 0) {
    recommendations.push(
      `### 1. 🛡️ Defend Category Leadership\n` +
      `Run periodic weekly benchmarks to detect AI citation drift:\n` +
      `\`\`\`bash\n` +
      `open-geo probe "${scorecard.brand}" -d "${scorecard.domain}"\n` +
      `\`\`\``
    );
  }

  lines.push(recommendations.join("\n\n"));
  lines.push("");

  lines.push(FOOTER_WATERMARK);

  return lines.join("\n");
}

/**
 * Formats Technical Audit report to Markdown
 */
export function formatAuditMarkdownReport(audit: TechnicalAuditReport): string {
  const lines: string[] = [];

  lines.push(`# 🛠️ Technical & AI Readiness Audit: ${audit.url}`);
  lines.push(
    `> Tool: \`open-geo\` Community Edition | Target URL: \`${audit.url}\` | Health Score: **${audit.score} / 100** | Audited At: ${audit.timestamp}`
  );
  lines.push("");

  lines.push("## 📋 Key Audit Checklist");
  lines.push("");
  lines.push(`* **AI Agent Standard (llms.txt)**: ${audit.llmsTxt.details}`);
  lines.push(`* **Structured Data (JSON-LD)**: ${audit.schemaMarkup.details}`);
  lines.push(`* **Heading Hierarchy (H1/H2)**: H1 count: ${audit.headings.h1Count}, H2 count: ${audit.headings.h2Count} (${audit.headings.hierarchyValid ? "✅ Valid" : "⚠️ Needs Adjustment"})`);
  lines.push(`* **AI Search Crawler Whitelist**: ${audit.aiCrawlability.allowsAiBots ? "✅ All major AI search bots allowed" : "❌ Blocked AI crawlers detected"}`);
  lines.push("");

  if (audit.recommendations.length > 0) {
    lines.push("## 🔧 Actionable Recommendations");
    lines.push("");
    audit.recommendations.forEach((rec, i) => {
      lines.push(`${i + 1}. ${rec}`);
    });
    lines.push("");
  }

  lines.push(FOOTER_WATERMARK);

  return lines.join("\n");
}

/**
 * Formats Query Fan-out Output to Markdown
 */
export function formatFanoutMarkdownReport(fanout: FanoutOutput): string {
  const lines: string[] = [];

  lines.push(`# 🌐 Query Fan-out Intent Analysis: ${fanout.topic}`);
  lines.push(
    `> Tool: \`open-geo\` Community Edition | Topic: \`${fanout.topic}\` | Industry: \`${fanout.industry}\` | Total Sub-queries: **${fanout.totalQueries}** | Generated: ${new Date().toUTCString()}`
  );
  lines.push("");

  if (fanout.coverage) {
    lines.push("## 🎯 Brand Fan-out Coverage");
    lines.push("");
    lines.push(`* **Target Domain**: \`${fanout.coverage.domain}\``);
    lines.push(`* **Coverage Rate**: **${fanout.coverage.coverageRate}%** (${fanout.coverage.covered} / ${fanout.coverage.total})`);
    lines.push("");

    if (fanout.coverage.criticalGaps.length > 0) {
      lines.push("### 🚨 Critical Coverage Gaps");
      lines.push("| Uncovered Sub-query | Search Signal | Suggested Action |");
      lines.push("| :--- | :--- | :--- |");
      fanout.coverage.criticalGaps.forEach((gap) => {
        lines.push(`| **${gap.query}** | \`${gap.searchSignal}\` | ${gap.suggestedAction} |`);
      });
      lines.push("");
    }
  }

  lines.push("## 📂 5-Dimensional Intent Groups Breakdown");
  lines.push("");

  for (const group of fanout.groups) {
    lines.push(`### 🔹 ${group.label} (\`${group.intent}\`)`);
    lines.push("");
    lines.push("| Sub-query | Search Signal | Priority | Brand Status | Action Item |");
    lines.push("| :--- | :--- | :--- | :--- | :--- |");

    for (const q of group.queries) {
      const brandStatus =
        q.brandMentioned === true
          ? "✅ Mentioned"
          : q.brandMentioned === false
          ? "❌ Missing"
          : "➖ Not Probed";
      const priorityLabel =
        q.priority === "critical"
          ? "🔥 Critical"
          : q.priority === "high"
          ? "⚡ High"
          : "Normal";

      lines.push(
        `| ${q.query} | \`${q.searchSignal}\` | ${priorityLabel} | ${brandStatus} | ${q.suggestedAction} |`
      );
    }
    lines.push("");
  }

  lines.push(FOOTER_WATERMARK);

  return lines.join("\n");
}
